# Generated by Django 4.0.4 on 2022-04-21 20:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('ename', models.CharField(max_length=100)),
                ('egender', models.CharField(max_length=150)),
                ('eadd', models.CharField(max_length=200)),
                ('edept', models.CharField(choices=[('Hr', 'HR'), ('Marketing', 'Marketing'), ('Finance', 'Finance'), ('Sales', 'Sales')], max_length=100)),
                ('emobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('esal', models.FloatField()),
                ('eskills', models.CharField(max_length=100)),
            ],
        ),
    ]
